Axia_architectures:
  x86_64: amd64
  aarch64: arm64

axia_binaries_dir: "Axia-{{ Axia_version }}"

Axia_architecture: "{{ Axia_architectures[ansible_facts.architecture] }}"
Axia_archive: "Axia-{{ Axia_os }}-{{ Axia_architecture }}-{{ Axia_version }}.tar.gz"
Axia_release: "{{ Axia_releases.json | rejectattr('prerelease') | first }}"
Axia_os: "{{ ansible_facts.system | lower }}"
Axia_version: "{{ Axia_release.tag_name }}"

Axia_signer_keyid: D93080B0C0D5FE8B
Axia_signer_pubkey: "{{ lookup('file', 'Axia.gpg.key') }}"

repo_url: https://github.com/Axia-Tech/axiav2
repo_api_base: https://api.github.com
