axiago_architectures:
  x86_64: amd64
  aarch64: arm64

axia_binaries_dir: "axiago-{{ axiago_version }}"

axiago_architecture: "{{ axiago_architectures[ansible_facts.architecture] }}"
axiago_archive: "axiago-{{ axiago_os }}-{{ axiago_architecture }}-{{ axiago_version }}.tar.gz"
axiago_release: "{{ axiago_releases.json | rejectattr('prerelease') | first }}"
axiago_os: "{{ ansible_facts.system | lower }}"
axiago_version: "{{ axiago_release.tag_name }}"

axiago_signer_keyid: D93080B0C0D5FE8B
axiago_signer_pubkey: "{{ lookup('file', 'axiago.gpg.key') }}"

repo_url: https://github.com/Axia-Tech/axiav2
repo_api_base: https://api.github.com
