- name: Setup gpg key
  apt_key:
    url: https://downloads.axc.network/axiago.gpg.key
    state: present

- name: Setup axiago repo
  apt_repository:
    repo: deb https://downloads.axc.network/apt bionic main
    state: present

- name: Setup golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports 
    state: present

- name: Install go
  apt:
    name: golang
    state: latest

- name: Update git clone
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_folder }}"
    version: "{{ tag }}"
    update: yes
    force: yes

- name: Setup systemd
  template:
    src: templates/axiago.service.j2
    dest: /etc/systemd/system/axiago.service
    mode: 0755

- name: Create axia user
  user:
    name: "{{ ava_user }}"
    shell: /bin/bash
    uid: 114
    group: "{{ ava_group }}"

- name: Create axia config dir
  file:
    path: /etc/axiago
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create axia C config dir
  file:
    path: /etc/axiago/C
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create axia log dir
  file:
    path: "{{ log_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create axia database dir
  file:
    path: "{{ db_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create axia plugins directory
  file:
    path: "{{ plugin_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory
    recurse: yes

- name: Build axiago
  command: ./scripts/build.sh
  args:
    chdir: "{{ repo_folder }}"

- name: Copy axiago binaries to the correct location
  command: cp build/axiago /usr/local/bin/axiago
  args:
    chdir: "{{ repo_folder }}"

- name: Copy evm binaries to the correct location
  command: cp build/plugins/evm {{ plugin_dir }}
  args:
    chdir: "{{ repo_folder }}"


- name: Configure axia 
  template:
    src: templates/conf.json.j2
    dest: /etc/axiago/conf.json
    mode: 0644

- name: Configure axia C Chain
  template:
    src: templates/C/config.json.j2
    dest: /etc/axiago/C/config.json
    mode: 0644

- name: Enable Axia
  systemd:
    name: axiago
    enabled: yes
